In [1]:
pip install holidays

Requirement already satisfied: holidays in /srv/conda/envs/notebook/lib/python3.10/site-packages (0.36)
Requirement already satisfied: python-dateutil in /srv/conda/envs/notebook/lib/python3.10/site-packages (from holidays) (2.8.2)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from python-dateutil->holidays) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
%run -i 'fetch_weather_data.py'

=================== Start ===================
28-01-2021
2021-03-03
2021-04-06
2021-05-10
2021-06-13
2021-07-17
2021-08-20
2021-09-23
2021-10-27
2021-11-30
2022-01-03
2022-02-06
2022-03-12
2022-04-15
2022-05-19
2022-06-22
2022-07-26
2022-08-29
2022-10-02
2022-11-05
2022-12-09
2023-01-12
2023-02-15
2023-03-21
2023-04-24
2023-05-28
2023-07-01
2023-08-04
=================== Done ===================

In [4]:
# date parser
a_parser = lambda date: pd.to_datetime(date, format='%Y-%m-%d %H:%M')

# load the dataset
afit_dataframe = pd.read_csv(
    'all.csv', parse_dates=[0],
    index_col=[0], date_parser=a_parser, engine='python'
)

In [5]:
len(afit_dataframe)

22608

In [6]:
# date parser
d_parser = lambda date: pd.to_datetime(date, format=' %d-%m-%Y')

# load the dataset
afit_data = pd.read_csv(
    'AFIT.csv', parse_dates=[1, 2],
    index_col=[0], date_parser=d_parser, engine='python'
)

In [7]:
afit_data

     From Date    To Date   Consumption
S/N
1   2021-01-28 2021-02-26        901193
2   2021-02-26 2021-03-31       1196720
3   2021-03-31 2021-05-04       1368837
4   2021-05-04 2021-06-01       1010055
5   2021-06-01 2021-07-01       1182189
6   2021-07-01 2021-07-29        963249
7   2021-07-29 2021-08-31       1173269
8   2021-08-31 2021-09-30       1014862
9   2021-09-30 2021-10-30       1190668
10  2021-10-30 2021-11-25       1095559
11  2021-11-25 2021-12-22        996869
12  2021-12-22 2022-01-27       1113792
13  2022-01-27 2022-03-02       1115812
14  2022-03-02 2022-03-29       1149770
15  2022-03-29 2022-04-26       1268432
16  2022-04-26 2022-05-27       1239955
17  2022-05-27 2022-07-06       1234401
18  2022-07-06 2022-07-28        743982
19  2022-07-28 2022-08-28       1146045
20  2022-08-28 2022-09-28       1070607
21  2022-09-28 2022-10-31       1266069
22  2022-10-31 2022-11-29       1123413
23  2022-11-29 2022-12-22        813708
24  2022-12-22 2023-01-30       1359629
25  2023-01-30 2023-03-01       1061081
26  2023-03-01 2023-03-31       1206024
27  2023-03-31 2023-05-02       1262505
28  2023-05-02 2023-05-26       1054304
29  2023-05-26 2023-07-03       1519733
30  2023-07-03 2023-07-27       1051687
31  2023-07-27 2023-08-28       1256571

In [8]:
consumption = []

for i in range(len(afit_data.values)):
    x = abs((afit_data.values[i][0] - afit_data.values[i][1]).days) * 24
    y = np.random.multinomial(n=afit_data.values[i][2], pvals=[1/x] * x)
    consumption += list(y)

In [9]:
len(consumption)

22608

In [10]:
consumption[:10]

[1309, 1319, 1250, 1293, 1260, 1288, 1222, 1302, 1304, 1346]

In [11]:
afit_dataframe['ENERGY CONSUMPTION'] = [i for i in consumption]

In [12]:
afit_dataframe

,ENERGY CONSUMPTION,TEMPERATURE(C),PRESSURE,HUMIDITY,WEATHER CODE,WIND DIRECTION(DEGREE),WIND SPEED(KMPH),WORKDAY,PUBLIC HOLIDAY
DATE(HOURS/DAY/MONTH/YEAR),,,,,,,,,
2021-01-28 00:00:00,1309,24,1011,16,113,53,14,1,0
2021-01-28 01:00:00,1319,23,1011,15,113,55,15,1,0
2021-01-28 02:00:00,1250,23,1011,15,113,57,16,1,0
2021-01-28 03:00:00,1293,22,1011,14,113,59,17,1,0
2021-01-28 04:00:00,1260,21,1011,13,113,61,17,1,0
...,...,...,...,...,...,...,...,...,...
2023-08-27 19:00:00,1706,23,1012,97,353,235,11,0,0
2023-08-27 20:00:00,1656,23,1013,97,248,235,8,0,0
2023-08-27 21:00:00,1644,22,1014,97,353,223,10,0,0
2023-08-27 22:00:00,1583,22,1014,98,353,233,7,0,0
2023-08-27 23:00:00,1646,22,1015,98,353,251,8,0,0

In [13]:
afit_dataframe.to_csv('final AFIT data.csv')